require(nza)
require(nzr)
require(xgboost)
require(caTools)
require(caret)
require(pROC)



nzConnectDSN('DBM_SANDBOX')

if (nzExistTable('NZA_TEST')) nzDeleteTable('NZA_TEST')

nzQuery("CREATE TABLE DBM_SANDBOX..NZA_TEST AS
                SELECT *
                FROM (
                 SELECT DETAIL.LAST_NAME,
                 DETAIL.ADDRESS_LINE_1,
                 DETAIL.CITY_NAME,
                 DETAIL.STATE_CODE,
                 DETAIL.ZIP,
                 MAX(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-(365) AND CURRENT_DATE::DATE THEN 1 ELSE 0 END) AS PURCH_6MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-(365) AND CURRENT_DATE::DATE THEN DETAIL.SALES ELSE 0 END) AS SLS_6MO,
                 MAX(CASE WHEN DETAIL.REWARDS_ACTIVE_CODE IN ('A','Y') THEN 1 ELSE 0 END) AS REWARDS,
                 MAX(CASE WHEN DETAIL.VISA_STATUS = 'Y' THEN 1 ELSE 0 END) AS VISA,
                 MIN(DETAIL.DATE_VALUE) AS FIRST_DATE,
                 MAX(DETAIL.DATE_VALUE) AS LAST_DATE,
                 MAX(DETAIL.DATE_VALUE)-MIN(DETAIL.DATE_VALUE) AS TIME_AS_CUSTOMER,
                 COUNT(DISTINCT DETAIL.INBOUND_INTERACTION_KEY) AS ORDERS_LT,
                 (MAX(DETAIL.DATE_VALUE) - MIN(DETAIL.DATE_VALUE)) / NULLIF(COUNT(DISTINCT DETAIL.INBOUND_INTERACTION_KEY), 0)::DOUBLE AS AVG_DAYS_BTW_PURCH,
                 NVL(SUM(DETAIL.SALES)/NULLIF(COUNT(DISTINCT DETAIL.INBOUND_INTERACTION_KEY),0)::DOUBLE,0) AS AVG_TICKET_LT,
                 NVL(SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE THEN DETAIL.SALES ELSE 0 END) /
                 NULLIF(COUNT(DISTINCT CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE THEN DETAIL.INBOUND_INTERACTION_KEY ELSE NULL END),0),0) AS AVG_TICKET_24MO, 
                 NVL(SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE THEN DETAIL.SALES ELSE 0 END) /
                 NULLIF(COUNT(DISTINCT CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE THEN DETAIL.INBOUND_INTERACTION_KEY ELSE NULL END),0),0) AS AVG_TICKET_48MO,
                 SUM(CASE WHEN DETAIL.CHANNEL_GROUP = 'RETAIL' THEN DETAIL.SALES ELSE 0 END)/ NULLIF(SUM(DETAIL.SALES),0) AS PERCENT_RETAIL_SALES,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE THEN DETAIL.SALES ELSE 0 END) AS SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-365 AND CURRENT_DATE::DATE THEN DETAIL.SALES ELSE 0 END) AS SALES_12MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER IN (100, 151, 200, 400, 450) THEN DETAIL.SALES ELSE 0 END) AS CORE_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 100 THEN DETAIL.SALES ELSE 0 END) AS D100_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 151 THEN DETAIL.SALES ELSE 0 END) AS D151_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 175 THEN DETAIL.SALES ELSE 0 END) AS D175_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 200 THEN DETAIL.SALES ELSE 0 END) AS D200_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 300 THEN DETAIL.SALES ELSE 0 END) AS D300_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 350 THEN DETAIL.SALES ELSE 0 END) AS D350_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 400 THEN DETAIL.SALES ELSE 0 END) AS D400_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 450 THEN DETAIL.SALES ELSE 0 END) AS D450_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 475 THEN DETAIL.SALES ELSE 0 END) AS D475_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 500 THEN DETAIL.SALES ELSE 0 END) AS D500_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 600 THEN DETAIL.SALES ELSE 0 END) AS D600_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 650 THEN DETAIL.SALES ELSE 0 END) AS D650_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-729 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 675 THEN DETAIL.SALES ELSE 0 END) AS D675_SALES_24MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER IN (100, 151, 200, 400, 450) THEN DETAIL.SALES ELSE 0 END) AS CORE_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 100 THEN DETAIL.SALES ELSE 0 END) AS D100_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 151 THEN DETAIL.SALES ELSE 0 END) AS D151_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 175 THEN DETAIL.SALES ELSE 0 END) AS D175_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 200 THEN DETAIL.SALES ELSE 0 END) AS D200_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 300 THEN DETAIL.SALES ELSE 0 END) AS D300_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 350 THEN DETAIL.SALES ELSE 0 END) AS D350_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 400 THEN DETAIL.SALES ELSE 0 END) AS D400_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 450 THEN DETAIL.SALES ELSE 0 END) AS D450_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 475 THEN DETAIL.SALES ELSE 0 END) AS D475_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 500 THEN DETAIL.SALES ELSE 0 END) AS D500_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 600 THEN DETAIL.SALES ELSE 0 END) AS D600_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 650 THEN DETAIL.SALES ELSE 0 END) AS D650_SALES_48MO,
                 SUM(CASE WHEN DETAIL.DATE_VALUE BETWEEN CURRENT_DATE::DATE-1458 AND CURRENT_DATE::DATE AND DETAIL.DEPARTMENT_MEMBER_NUMBER = 675 THEN DETAIL.SALES ELSE 0 END) AS D675_SALES_48MO
                 FROM (
                 SELECT IND.LAST_NAME,
                 ADDR.ADDRESS_LINE_1,
                 ADDR.CITY_NAME,
                 ADDR.STATE_CODE,
                 ADDR.ZIP,
                 IND.REWARDS_ACTIVE_CODE,
                 IND.VISA_STATUS,
                 DT.DATE_VALUE,
                 SH.INBOUND_INTERACTION_KEY,
                 ST.CHANNEL_GROUP,
                 PD.DEPARTMENT_MEMBER_NUMBER,
                 PD.SUB_DEPARTMENT_MEMBER_NUMBER,
                 SUM(SD.SALE_QUANTITY) AS UNITS,
                 SUM(SD.SALES_PRICE) AS SALES
                 FROM EDW_SPOKE..FACT_BPS_SALES_HEADER SH
                 JOIN EDW_SPOKE..FACT_BPS_SALES_DETAIL SD ON SH.INBOUND_INTERACTION_KEY = SD.SH_INBOUND_INTERACTION_KEY
                 JOIN EDW_SPOKE..DIM_STORE ST ON SD.STORE_MEMBER_KEY = ST.MEMBER_KEY
                 JOIN EDW_SPOKE..DIM_DATE DT ON SD.SALE_DATE_KEY = DT.DATE_KEY
                 JOIN EDW_SPOKE..DIM_PRODUCT_BPS PD ON SD.SALES_PRODUCT_MEMBER_KEY = PD.MEMBER_KEY
                 JOIN EDW_SPOKE..DIM_PERSONA PERS ON SH.CUSTOMER_MEMBER_KEY = PERS.MEMBER_KEY
                 JOIN EDW_SPOKE..DIM_INDIVIDUAL IND ON PERS.INDIVIDUAL_MEMBER_KEY = IND.MEMBER_KEY
                 JOIN EDW_SPOKE..DIM_ADDRESS ADDR ON IND.ADDRESS_KEY = ADDR.MEMBER_KEY
                 WHERE ST.CHANNEL_GROUP IN ('DIRECT','RETAIL')
                 AND DT.DATE_VALUE BETWEEN CURRENT_DATE::DATE - (365*5) AND CURRENT_DATE::DATE
                 AND SD.ACTUAL_SALE_FLAG = 'Y'
                 AND SD.RETURN_FLAG <> 'Y'
                 AND PD.DEPARTMENT_MEMBER_NUMBER NOT IN (875,999)
                 GROUP BY IND.LAST_NAME, ADDR.ADDRESS_LINE_1, ADDR.CITY_NAME, ADDR.STATE_CODE, ADDR.ZIP, IND.REWARDS_ACTIVE_CODE, IND.VISA_STATUS, DT.DATE_VALUE, 
                 SH.INBOUND_INTERACTION_KEY, ST.CHANNEL_GROUP, PD.DEPARTMENT_MEMBER_NUMBER, PD.SUB_DEPARTMENT_MEMBER_NUMBER
                 ORDER BY IND.LAST_NAME, ADDR.ADDRESS_LINE_1, ADDR.CITY_NAME, ADDR.STATE_CODE, ADDR.ZIP, DT.DATE_VALUE, SH.INBOUND_INTERACTION_KEY,
                 PD.DEPARTMENT_MEMBER_NUMBER, PD.SUB_DEPARTMENT_MEMBER_NUMBER
                 ) AS DETAIL
                 GROUP BY DETAIL.LAST_NAME, DETAIL.ADDRESS_LINE_1, DETAIL.CITY_NAME, DETAIL.STATE_CODE, DETAIL.ZIP
                ) AS A
                WHERE A.AVG_TICKET_48MO > 0")

if (nzExistTable('CHURNMODEL')) nzDeleteTable('CHURNMODEL')

nzQuery('CREATE TABLE DBM_SANDBOX..CHURNMODEL AS
         SELECT LAST_NAME,
                ADDRESS_LINE_1,
                CITY_NAME,
                STATE_CODE,
                ZIP,
                (ORDERS_LT - AVG(ORDERS_LT) OVER()) / STDDEV(ORDERS_LT) OVER() AS ORDERS_LT,
                (AVG_DAYS_BTW_PURCH - AVG(AVG_DAYS_BTW_PURCH) OVER()) / STDDEV(AVG_DAYS_BTW_PURCH) OVER() AS AVG_DAYS_BTW_PURCH,
                (AVG_TICKET_LT - AVG(AVG_TICKET_LT) OVER()) / STDDEV(AVG_TICKET_LT) OVER() AS AVG_TICKET_LT,
                (TIME_AS_CUSTOMER - AVG(TIME_AS_CUSTOMER) OVER()) / STDDEV(TIME_AS_CUSTOMER) OVER() AS TIME_AS_CUSTOMER,
                (SALES_12MO - AVG(SALES_12MO) OVER()) / STDDEV(SALES_12MO) OVER() AS SALES_12MO,
                (CORE_SALES_24MO - AVG(CORE_SALES_24MO) OVER()) / STDDEV(CORE_SALES_24MO) OVER() AS CORE_SALES_24MO,
                (D200_SALES_24MO - AVG(D200_SALES_24MO) OVER()) / STDDEV(D200_SALES_24MO) OVER() AS D200_SALES_24MO,
                (D350_SALES_24MO - AVG(D350_SALES_24MO) OVER()) / STDDEV(D350_SALES_24MO) OVER() AS D350_SALES_24MO,
                (D400_SALES_24MO - AVG(D400_SALES_24MO) OVER()) / STDDEV(D400_SALES_24MO) OVER() AS D400_SALES_24MO,
                (D450_SALES_24MO - AVG(D450_SALES_24MO) OVER()) / STDDEV(D450_SALES_24MO) OVER() AS D450_SALES_24MO,
                PURCH_6MO,
                REWARDS,
                VISA
        FROM DBM_SANDBOX..NZA_TEST
        limit 1000')

target <-c('TARGET_RESPONSE')
finalvars <- c('ORDERS_LT','AVG_DAYS_BTW_PURCH','AVG_TICKET_LT', 'TIME_AS_CUSTOMER',
               'SALES_12MO','CORE_SALES_24MO', 'D200_SALES_24MO', 'D350_SALES_24MO',
               'D400_SALES_24MO','D450_SALES_24MO','PURCH_6MO','REWARDS', 'VISA')

nzChurn <- nz.data.frame('CHURNMODEL')
head(nzChurn)


bst <- xgb.load('C:\\Users\\pairwin\\Documents\\GitHub\\RAnalyses\\xgboost_churn.model')

load("C:\\Users\\pairwin\\Documents\\GitHub\\RAnalyses\\CHURN_LOGISTIC.rda") #logmod


pred <- function(x, model1) {
 predval <- predict(model1, data.frame(LAST_NAME=as.character(x[[1]]),
                             ADDRESS_LINE_1=as.character(x[[2]]),
                             CITY_NAME=as.character(x[[3]]),
                             STATE_CODE=as.character(x[[4]]),
                             ZIP=as.character(x[[5]]),
                          ORDERS_LT=as.numeric(x[[6]]),
                          AVG_DAYS_BTW_PURCH=as.numeric(x[[7]]),
                          AVG_TICKET_LT=as.numeric(x[[8]]),
                          TIME_AS_CUSTOMER=as.numeric(x[[9]]),
                          SALES_12MO=as.numeric(x[[10]]),
                          CORE_SALES_24MO=as.numeric(x[[11]]),
                          D200_SALES_24MO=as.numeric(x[[12]]),
                          D350_SALES_24MO=as.numeric(x[[13]]),
                          D400_SALES_24MO=as.numeric(x[[14]]),
                          D450_SALES_24MO=as.numeric(x[[15]]),
                          PURCH_6MO=factor(x[[16]],levels=c(1,0)),
                          REWARDS=factor(x[[17]], levels=c(1,0)),
                          VISA=factor(x[[18]], levels=c(1,0))))
 return(predval)
}

nzApply(nzChurn,
        FUN=pred, 
        model1=logmod, 
        output.name='CHURNSCORED',
        clear.existing=TRUE,                                          
        # output.signature = list(LAST_NAME=list(NZ.NATIONAL_VARIABLE,30),
        #                         ADDRESS_LINE_1=list(NZ.NATIONAL_VARIABLE,30),
        #                         CITY_NAME=list(NZ.NATIONAL_VARIABLE,30),
        #                         STATE_CODE=list(NZ.NATIONAL_VARIABLE,30),
        #                         ZIP=list(NZ.NATIONAL_VARIABLE,30),
        #                         ORDERS_LT=NZ.DOUBLE,
        #                         AVG_DAYS_BTW_PURCH=NZ.DOUBLE,
        #                         AVG_TICKET_LT=NZ.DOUBLE,
        #                         TIME_AS_CUSTOMER=NZ.DOUBLE,
        #                         SALES_12MO=NZ.DOUBLE,
        #                         CORE_SALES_24MO=NZ.DOUBLE,
        #                         D200_SALES_24MO=NZ.DOUBLE,
        #                         D350_SALES_24MO=NZ.DOUBLE,
        #                         D400_SALES_24MO=NZ.DOUBLE,
        #                         D450_SALES_24MO=NZ.DOUBLE,
        #                         PURCH_6MO=NZ.INT64,
        #                         REWARDS=NZ.INT64,
        #                         VISA=NZ.INT64,
        #                         SCORE=NZ.DOUBLE))
        output.signature = list(SCORE=NZ.DOUBLE))

nzDisconnect()
