library(RODBC)
library(arules)
require(arulesViz)

ch <- odbcConnect("DBM_SANDBOX", believeNRows=FALSE)
nzdata <- sqlQuery(ch, paste("
SELECT B.TRANSACTION_ID,
	   MAX(CASE WHEN ROWNUM = 1 THEN B.CLASS ELSE NULL END) AS CLASS1,
     MAX(CASE WHEN ROWNUM = 2 THEN B.CLASS ELSE NULL END) AS CLASS2,
     MAX(CASE WHEN ROWNUM = 3 THEN B.CLASS ELSE NULL END) AS CLASS3,
     MAX(CASE WHEN ROWNUM = 4 THEN B.CLASS ELSE NULL END) AS CLASS4,
     MAX(CASE WHEN ROWNUM = 5 THEN B.CLASS ELSE NULL END) AS CLASS5,
     MAX(CASE WHEN ROWNUM = 6 THEN B.CLASS ELSE NULL END) AS CLASS6,
     MAX(CASE WHEN ROWNUM = 7 THEN B.CLASS ELSE NULL END) AS CLASS7,
     MAX(CASE WHEN ROWNUM = 8 THEN B.CLASS ELSE NULL END) AS CLASS8,
     MAX(CASE WHEN ROWNUM = 9 THEN B.CLASS ELSE NULL END) AS CLASS9,
     MAX(CASE WHEN ROWNUM = 10 THEN B.CLASS ELSE NULL END) AS CLASS10,
     MAX(CASE WHEN ROWNUM = 11 THEN B.CLASS ELSE NULL END) AS CLASS11,
     MAX(CASE WHEN ROWNUM = 12 THEN B.CLASS ELSE NULL END) AS CLASS12,
     MAX(CASE WHEN ROWNUM = 13 THEN B.CLASS ELSE NULL END) AS CLASS13,
     MAX(CASE WHEN ROWNUM = 14 THEN B.CLASS ELSE NULL END) AS CLASS14,
     MAX(CASE WHEN ROWNUM = 15 THEN B.CLASS ELSE NULL END) AS CLASS15
     FROM (
     SELECT A.TRANSACTION_ID,
     A.SKU_DISPLAY_NUMBER || ' - ' || A.SKU_NAME AS CLASS,
     A.SALES,
     ROW_NUMBER() OVER(PARTITION BY A.TRANSACTION_ID ORDER BY A.SALES DESC) AS ROWNUM
     FROM (
     SELECT SH.INBOUND_INTERACTION_KEY AS TRANSACTION_ID,
     PD.SKU_DISPLAY_NUMBER,
     PD.SKU_NAME,
     SUM(SD.SALES_PRICE) AS SALES
     FROM EDW_SPOKE..FACT_BPS_SALES_HEADER SH
     JOIN EDW_SPOKE..FACT_BPS_SALES_DETAIL SD ON SH.INBOUND_INTERACTION_KEY = SD.SH_INBOUND_INTERACTION_KEY
     JOIN EDW_SPOKE..DIM_STORE ST ON SD.STORE_MEMBER_KEY = ST.MEMBER_KEY
     JOIN EDW_SPOKE..DIM_DATE DT ON SH.TRANSACTION_DATE_KEY = DT.DATE_KEY
     JOIN EDW_SPOKE..DIM_PRODUCT_BPS PD ON SD.SALES_PRODUCT_MEMBER_KEY = PD.MEMBER_KEY
     WHERE DT.FISCAL_YEAR >= 2016
     AND ST.CHANNEL_GROUP IN ('DIRECT','RETAIL')
     AND PD.SKU_DISPOSITION_CODE IN ('A','N')
     AND SD.RETURN_FLAG <> 'Y'
     AND SD.ACTUAL_SALE_FLAG = 'Y'
     AND PD.SUB_DEPARTMENT_DISPLAY_NUMBER <> '0700-0740'
     AND PD.DEPARTMENT_MEMBER_NUMBER NOT IN (875, 999)
     GROUP BY 1,2,3
     ORDER BY 1,3 DESC
     ) AS A
     ) AS B
     GROUP BY 1
     HAVING CLASS2 IS NOT NULL
     "))

nzdata$TRANSACTION_ID <- NULL
tData <- as (nzdata, 'transactions')
size(head(tData))
LIST(head(tData, 3))

frequentItems <- eclat(tData, parameter = list(supp = 0.0001, minlen = 2))
inspect(head(frequentItems))

itemFrequencyPlot(tData, topN=10, type='absolute', main='Item Frequency')

item <- 'CLASS1=1620147 - 360 QUALIFIER BACKPACK'

rules <- apriori(tData, parameter = list(supp=0.00001, conf=0.15, minlen = 2, maxtime=10), 
                 appearance=list(default='lhs', rhs=item),
                 control = list(verbose=F))
rules_conf <- sort(rules, by='confidence', decreasing=TRUE)
inspect(head(rules_conf))

plot(rules)

plotly_arules(rules)
inspectDT(rules)
