require(nzr)
nzConnect(user='pairwin',password='pairwin',machine='srvdwhitp01',database='DBM_SANDBOX')

#t <- nz.data.frame('PI_TABMODELING')

t <- nzQuery('SELECT * FROM DBM_SANDBOX..PI_TABMODELING')


collist = c('TARGET_PURCH_NEXT15','MEDHINC_CY','MEDAGE_CY','CLOSEST_BP','CLOSEST_CAB','MALES_IN_HOUSHOLD',
            'FEMALES_IN_HOUSHOLD','REWARDS_CUSTOMER', 'DAYS_AS_CUSTOMER','TOTAL_TRANSACTIONS','REW_TRANSACTIONS',
            'TOTAL_SPEND','FISH_SALES','HUNT_SALES','OTHER_SALES', 'TRANSACTIONS_QMIN1','SPEND_QMIN1',
            'TRANSACTIONS_QMIN2','SPEND_QMIN2','TRANSACTIONS_QMIN3','SPEND_QMIN3','TRANSACTIONS_QMIN4',
            'SPEND_QMIN4','FISH_SALES_QMIN1','HUNT_SALES_QMIN1','OTHER_SALES_QMIN1','FISH_SALES_QMIN2',
            'HUNT_SALES_QMIN2','OTHER_SALES_QMIN2','FISH_SALES_QMIN3','HUNT_SALES_QMIN3','OTHER_SALES_QMIN3',
            'FISH_SALES_QMIN4','HUNT_SALES_QMIN4','OTHER_SALES_QMIN4','DAYS_SINCE_PURCHASE','RTL_FLAG',
            'INT_FLAG','CAT_FLAG','AVERAGE_TICKET','AVERAGE_TICKET_QMIN1', 'AVERAGE_TICKET_QMIN2',
            'AVERAGE_TICKET_QMIN3','AVERAGE_TICKET_QMIN4','DAYS_BTWN_PURCHASE','CHANNEL_HIST','CHANNEL_HIST_QMIN1',
            'CHANNEL_HIST_QMIN2','CHANNEL_HIST_QMIN3','CHANNEL_HIST_QMIN4','CUSTOMER_TYPE','CUSTOMER_TYPE_QMIN1',
            'CUSTOMER_TYPE_QMIN2','CUSTOMER_TYPE_QMIN3','CUSTOMER_TYPE_QMIN4', 'IND_IN_HH')

collist_cont = c('MEDHINC_CY','MEDAGE_CY','CLOSEST_BP','CLOSEST_CAB','MALES_IN_HOUSHOLD','FEMALES_IN_HOUSHOLD',
                'DAYS_AS_CUSTOMER','TOTAL_TRANSACTIONS','REW_TRANSACTIONS','TOTAL_SPEND','FISH_SALES',
                'HUNT_SALES','OTHER_SALES','TRANSACTIONS_QMIN1','SPEND_QMIN1','TRANSACTIONS_QMIN2',
                'SPEND_QMIN2','TRANSACTIONS_QMIN3','SPEND_QMIN3','TRANSACTIONS_QMIN4','SPEND_QMIN4',
                'FISH_SALES_QMIN1','HUNT_SALES_QMIN1','OTHER_SALES_QMIN1','FISH_SALES_QMIN2','HUNT_SALES_QMIN2',
                'OTHER_SALES_QMIN2','FISH_SALES_QMIN3','HUNT_SALES_QMIN3','OTHER_SALES_QMIN3','FISH_SALES_QMIN4',
                'HUNT_SALES_QMIN4','OTHER_SALES_QMIN4','DAYS_SINCE_PURCHASE','AVERAGE_TICKET',
                'AVERAGE_TICKET_QMIN1', 'AVERAGE_TICKET_QMIN2','AVERAGE_TICKET_QMIN3','AVERAGE_TICKET_QMIN4',
                'DAYS_BTWN_PURCHASE','IND_IN_HH')

collist_bin = c('REWARDS_CUSTOMER','RTL_FLAG','INT_FLAG','CAT_FLAG')

collist_cat = c('CHANNEL_HIST','CHANNEL_HIST_QMIN1','CHANNEL_HIST_QMIN2','CHANNEL_HIST_QMIN3',
                'CHANNEL_HIST_QMIN4','CUSTOMER_TYPE','CUSTOMER_TYPE_QMIN1','CUSTOMER_TYPE_QMIN2',
                'CUSTOMER_TYPE_QMIN3','CUSTOMER_TYPE_QMIN4')

idx <- match(collist, names(t))
fulldata <- t[, idx]


idx <- match(collist_cont, names(t))
fulldata_cont <- t[, idx]

median_impute <- function(x){
  function(x) {
  
    x[is.na(x)] <- median(x, na.rm=T);
  
  }
  apply(x)
}

for(i in names(fulldata_cont)) {
  hist(fulldata_cont[[paste(i)]],
       breaks=100)
}

nzDisconnect()
